# fly.toml app configuration file generated for titanic-js-api on 2023-08-09T14:53:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanic-js-api"
primary_region = "nrt"

[build]
  dockerfile = "./api/Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
